# the deep learning revolution (3)

**Machine learning** (ML) today is one of the most important, and fastest growing, fields of technology. Applications of machine learning are becoming ubiquitous, and solutions learned from data are increasingly displacing traditional hand-crafted algorithms. This has not only led to improved performance for existing technologies but has opened the door to a vast range of new capabilities that would be inconceivable if new algorithms had to be designed explicitly by hand.

One particular branch of machine learning, known as **deep learning** (DL), has emerged as an exceptionally powerful and general-purpose framework for learning from data. Deep learning is based on computational models called neural networks which were originally inspired by mechanisms of learning and information processing in the human brain.

The field of **artificial intelligence** (AI), seeks to recreate the powerful capabilities of the brain in machines, using machine learning methods. Many of the AI systems in current use represent applications of machine learning which are designed to solve very specific and focused problems, and while these are extremely useful they fall far short of the tremendous breadth of capabilities of the human brain. This has led to the introduction of the term **artificial general intelligence** (AGI), to describe the aspiration of building machines with this much greater flexibility.  After many decades of steady progress, machine learning has now entered a phase of very rapid development. Recently, massive deep learning systems called **large language models** (LLMs) have started to exhibit remarkable capabilities that have been described as the first indications of artificial general intelligence.

Will LLMs help us achieve the leap from AI to AGI? This is a question hotly debated everyday everwhere; only time will tell.