---
title: "Standard distributions"
---

After introducing probability theory, it's natural to introduce some concrete example distributions. These distributions will be the backbone of our modeling exercise.

The first use of modeling data with probability distributions is density estimation. Here we assign a certain distribution to the data, and then determine the parameters of the distribution to best fit the data.
Density estimation is always an ill-posed problem, because as long as a distribution has support for the data, there is always chance of that distribution producing the data, albeit the probability might be slim. 

Parameterized distributions can fell short for real world complex data non-parameterized methods still have parameters, just that the parameters serve a different purpose. For parameterized distributions they are used to determine the shape of the distribution, while for non-parameterized methods, they decide the model complexity.

And model complexity can grow rapidly with data size.

Deep neural nets offer the best of both worlds.


## Discrete variables

### Bernoulli distribution

### Binomial distribution

### Multinomial distribution

## The multivariate Gaussian

### Geometry of the Gaussian

### Moments

### Limitations

### Conditional distribution

### Marginal distribution

### Bayes' theorem

### Maximum likelihood

### Sequential estimation

### mixture of Gaussians

## Periodic variables

### von Mises distribution

## The exponential family

$$
p(\mathbf{x}|\mathbf{\eta}) = h(\mathbf{x})g(\mathbf{\eta}) \exp\{\mathbf{\eta}^T \mathbf{u}(\mathbf{x})\}
$$

The four key elements of the exponential family are:

- base measure
- partition function
- natural parameter
- sufficient statistics

### Sufficient statistics

Due to the formula constraint of the exponential family, any information about the data that is not in the sufficient statistics is lost.

## Nonparametric methods

### Histograms

### Kernel density

### Nearest neighbors
