---
title: "Single layer networks: regression"
---

In machine learning we often use x to denote the input data and y to denote the target. If we only have x but not y, this is a unsupervised learning problem, which means that we have some data, but we don't specifically have a task to take advantage of them. In this case we can use the probability theory we have just introduced to model their distributions. If we have both x and y, we'd often want to know how having x giving rise to the realization of y, and this will be a supervised learning problem. In this case not only do we want to model the distribution of y, we also want to know how the distribution of y can be affected by the value of x.

Depending on the nature of y supervised learning problems can be further categorized into regression and classification. Regression when y is continuous and classification when it's discrete. We can talk about regression and classification all day long: they are the backbone of many statistical models used in many natural science and social science fields. But here we are only using them as components of deep neural networks, which we plan to build in later chapters.

## linear regression

### basis function

### likelihood function

### maximum likelihood

### geometry of least squares

### sequential learning

### regularised least squares

### multiple outputs

## decision theory

## the bias-variance trade-off
