project:
  type: book
  output-dir: docs

book:
  title: "dlfc_notes"
  author: "Olivier Ma"
  date: "6/4/2024"
  chapters:
    - index.qmd
    - 01.qmd
    - 02.qmd
    - 04.qmd
    - 07.qmd
    - 14.qmd
    - 18.qmd
    - 20.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



