# Preface {.unnumbered}

*This project is a Work In Early Progress(WIeP).*

I'm a great fan of Bishop's 2006 book, Pattern Recognition and Machine Learning (PRML), so as an AI practioner coming from a Bayesian background, I'm quite happy to learn that Bishop (and Bishop) have published a new book dedicated to deep learning and artificial intelligence. 
The focus on generative models is especially enticing, firstly because it is all the rage for the moment; secondly for a Bayesian statistician, doing generative modeling has always been what we are trained for.

The book has 20 chapters, I have divided them roughly into three parts.

- Foundations: chapters 1-5, covering the basics of machine learning.
- Deep Learning: chapters 6-13, covering the nuts and bolts of deep learning.
- Generative Models: chapters 14-20, covering generative modeling and some common model architectures.

Herein collected are my notes of the book, and the code to implement some concepts from the book. 
Since these are my understanding of the book, they might not be completely accurate, so do refer to the book for the most accurate description. 
And let me know if you find any errors!

The notes and code are written in a literate programming style (See @knuth84 for additional discussion). 
A large portion of the code is borrowed from [Kevin Murphy's books](https://probml.github.io/pml-book/), same as some supplementary material in the notes. 